import 'package:app_muevete/models/exercise.dart';

class ExersiceService {
  List<Exercise> getEjersiciosPrimerNivel() {
    return [
      new Exercise(
          "SENTADILLA EN LA PARED",
          "Apoyar la espalda y la cabeza a la pared, separar los pies y bajar el cuerpo. Las rodillas y cadera deben formar un ángulo recto; muslos deben estar paralelos al piso",
          "1",
          'activ_fisica_lvl1_1.png',
          "",
          "",
          "",
          "1",
          "1",
          "Alex"),
      new Exercise(
          "NCLINACIONES LATERALESDE TRONCO",
          "De pie, con piernas separadas a la altura de las caderas. Inclinarse al lado derecho de manera alternativa con brazos paralelos al cuerpo, apretando la zona. Realice el movimiento de manera alternada. ",
          "2",
          'activ_fisica_lvl1_2.png',
          "",
          "",
          "",
          "2",
          "1",
          "Alex"),
      new Exercise(
          "PUENTE DE GLÚTEOS",
          "En posición supina con la espalda completamente estirada y rodillas flexionadas, con los pies a la línea de la cadera, brazos extendidos con la palma al piso. Elevar la cadera, apretando los glúteos por 1 a 2 seg, manteniendo la espalda y glúteos rectos.",
          "15",
          'activ_fisica_lvl1_3.png',
          "",
          "",
          "",
          "3",
          "1",
          "Alex"),
      new Exercise(
          "PANTORRILLAS",
          "Pararse recto con el apoyo de una silla (o en la pared), piernas ligeramente separadas, puntas de pie al frente. Con ambos pies, elevar los talones y bajarlos de manera lenta y continua.",
          "15",
          'activ_fisica_lvl1_4.png',
          "",
          "",
          "",
          "4",
          "1",
          "Alex"),
      new Exercise(
          "JUMPING JACKS",
          "Piernas levemente separadas y brazos paralelos al piso, saltar separando las piernas y llevando los brazos completamente estirados sobre la cabeza (juntar las palmas), saltar otra vez y llegar a la posición inicial. Realizar el ejercicio de manera continua.",
          "15",
          'activ_fisica_lvl1_5.png',
          "",
          "",
          "",
          "5",
          "1",
          "Alex"),
      new Exercise(
          "PATADA AL FRENTE",
          "Piernas levemente separadas, elevar cada una de ellas de manera intercalada hacia el frente de la persona, de manera recta. Tratar de tocar con la mano contraria la punta del pie elevado.",
          "15",
          'activ_fisica_lvl1_6.png',
          "",
          "",
          "",
          "6",
          "1",
          "Alex"),
      new Exercise(
          "ABDOMINALES DE PIE",
          "Espalda recta, colocar las manos detrás de la cabeza. Flexiona levemente las rodillas elevándola hacia el abdomen, tratando que la rodilla toque el codo contrario (pierna izquierda, hacia el codo derecho y viceversa). Conservar siempre la espalda recta",
          "15",
          'activ_fisica_lvl1_7.png',
          "",
          "",
          "",
          "7",
          "1",
          "Alex"),
      new Exercise(
          "DORSALES",
          "Acostarse en posición prono (boca abajo) completamente estirado. Brazos estirados hacia delante y dedos de los pies estirados hacia fuera. Elevar las piernas y brazos en simultáneo a la misma altura, sin dejar caer al piso.",
          "15",
          'activ_fisica_lvl1_8.png',
          "",
          "",
          "",
          "8",
          "1",
          "Alex"),
    ];
  }
}
